[project]
name = "python-django-blog-website-main"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "crispy-bootstrap4>=2025.6",
    "django>=5.2.9",
    "django-crispy-forms>=2.5",
    "pillow>=12.0.0",
]
